SQLALCHEMY_DATABASE_URI ='sqlite:///data.db' 
SQLALCHEMY_TRACK_MODIFICATIONS=True

ADMIN_USERNAME='admin'
ADMIN_PASSWORD=b'$2b$12$9b6h3.H0HIknJAf0vTlyg..tM.dHTOvJDCLO48F04DP7o1zO6KA7m' 
BCRYPT_LOG_ROUNDS = 5